"""Codex — REAL GitHub integration.

Pipeline (works end-to-end):
  1. POST /codex/api/github/connect   {token}
     → validates with GitHub /user, persists token+username on user.
  2. POST /codex/api/jobs              {prompt, repo_name?}
     → background worker:
        a. status=generating  — calls codex AiModel to produce file manifest
        b. status=creating-repo — POST /user/repos
        c. status=pushing — PUT each file via Contents API
        d. status=done, repo_url=<html_url>

Daily compute limit (4h) is enforced for PLUS users.

Note: full Codespace auto-debug loop is *not* included; the AI generates
the project, opens a real public repo, and returns the link. From there
the user can run / debug locally or open a Codespace manually.
"""
import base64
import json
import re
import threading
import time
from datetime import datetime, timedelta
from functools import wraps

import requests
from flask import Blueprint, request, jsonify, render_template, abort, current_app
from flask_login import login_required, current_user

from .db import db
from .models import Chat, Message, AiModel, CodexJob, CodexUsage, User
from . import ai_service

bp = Blueprint("codex", __name__, url_prefix="/codex")
GITHUB_API = "https://api.github.com"


# --- helpers -----------------------------------------------------------------
def get_or_create_codex_chat(user):
    chat = Chat.query.filter_by(user_id=user.id, is_codex=True).first()
    if chat:
        return chat
    chat = Chat(user_id=user.id, title="Codex", is_codex=True, is_locked=True)
    db.session.add(chat)
    db.session.commit()
    return chat


def get_usage(user):
    u = CodexUsage.query.filter_by(user_id=user.id).first()
    if not u:
        u = CodexUsage(user_id=user.id, seconds_used_today=0)
        db.session.add(u)
        db.session.commit()
    u.reset_if_needed()
    db.session.commit()
    return u


def add_seconds(user_id, secs):
    u = CodexUsage.query.filter_by(user_id=user_id).first()
    if not u:
        u = CodexUsage(user_id=user_id, seconds_used_today=0)
        db.session.add(u)
    u.reset_if_needed()
    u.seconds_used_today = (u.seconds_used_today or 0) + int(secs)
    db.session.commit()


def parse_files_from_ai(text):
    """Parse AI output formatted as `=== file: <path> ===\\n<content>`.
    Falls back to a single README.md if no markers detected."""
    pattern = re.compile(r"=== file: (.+?) ===\s*\n(.*?)(?=\n=== file: |\Z)", re.DOTALL)
    files = [(m.group(1).strip(), m.group(2).rstrip()) for m in pattern.finditer(text)]
    if not files:
        files = [("README.md", text.strip() or "# Generated by AurexAi Codex")]
    # de-dup paths and drop empty
    seen = {}
    for p, c in files:
        if p and c is not None:
            seen[p] = c
    return list(seen.items())


def safe_repo_name(name, prompt=""):
    name = (name or prompt).strip()[:60]
    name = re.sub(r"[^a-zA-Z0-9._-]+", "-", name).strip("-").lower()
    if not name:
        name = "aurex-codex-" + datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    return name[:50]


# --- routes ------------------------------------------------------------------
@bp.route("/")
@login_required
def codex_page():
    return render_template("codex.html")


@bp.route("/api/status")
@login_required
def status():
    plan = current_user.active_plan
    if plan != "PLUS" and not current_user.is_admin:
        return jsonify({
            "ok": True, "unlocked": False, "plan": plan,
            "message": "Codex faqat PLUS tarifida mavjud."
        })
    usage = get_usage(current_user)
    chat = get_or_create_codex_chat(current_user)
    limit = current_app.config["CODEX_DAILY_LIMIT_SECONDS"]
    return jsonify({
        "ok": True, "unlocked": True, "plan": plan,
        "chat_id": chat.id,
        "seconds_used": usage.seconds_used_today,
        "seconds_limit": limit,
        "seconds_remaining": max(0, limit - usage.seconds_used_today),
        "github_connected": bool(current_user.github_token),
        "github_username": current_user.github_username,
    })


@bp.route("/api/github/connect", methods=["POST"])
@login_required
def github_connect():
    token = (request.get_json(force=True).get("token") or "").strip()
    if not token:
        return jsonify({"ok": False, "error": "Token bo'sh."}), 400
    try:
        r = requests.get(
            f"{GITHUB_API}/user",
            headers={"Authorization": f"Bearer {token}",
                     "Accept": "application/vnd.github+json",
                     "X-GitHub-Api-Version": "2022-11-28"},
            timeout=15,
        )
    except Exception as e:
        return jsonify({"ok": False, "error": f"GitHub bilan ulanib bo'lmadi: {e}"}), 502

    if r.status_code != 200:
        return jsonify({
            "ok": False,
            "error": f"GitHub token noto'g'ri yoki yetarli ruxsatsiz ({r.status_code}). "
                     f"Scope'lar: repo, workflow, codespace kerak."
        }), 401

    data = r.json()
    current_user.github_token = token
    current_user.github_username = data.get("login")
    db.session.commit()
    return jsonify({"ok": True, "username": data.get("login"),
                    "name": data.get("name"), "avatar_url": data.get("avatar_url")})


@bp.route("/api/github/disconnect", methods=["POST"])
@login_required
def github_disconnect():
    current_user.github_token = None
    current_user.github_username = None
    db.session.commit()
    return jsonify({"ok": True})


@bp.route("/api/jobs", methods=["POST"])
@login_required
def submit_job():
    if current_user.active_plan != "PLUS" and not current_user.is_admin:
        abort(403)
    if not current_user.github_token:
        return jsonify({"ok": False, "error": "GitHub akkauntingizni avval ulang."}), 400

    usage = get_usage(current_user)
    limit = current_app.config["CODEX_DAILY_LIMIT_SECONDS"]
    if not current_user.is_admin and usage.seconds_used_today >= limit:
        return jsonify({"ok": False, "error": "Bugungi 4 soatlik Codex limiti tugadi. "
                                              "24 soatdan so'ng yangilanadi."}), 429

    data = request.get_json(force=True)
    prompt = (data.get("prompt") or "").strip()
    repo_name = safe_repo_name(data.get("repo_name") or "", prompt)
    if not prompt:
        return jsonify({"ok": False, "error": "Topshiriq bo'sh."}), 400

    job = CodexJob(user_id=current_user.id, prompt=prompt, status="queued")
    db.session.add(job)
    db.session.commit()

    chat = get_or_create_codex_chat(current_user)
    db.session.add(Message(chat_id=chat.id, role="user", content=prompt))
    db.session.commit()

    # Run pipeline in background
    app = current_app._get_current_object()
    threading.Thread(target=_run_codex_job,
                     args=(app, job.id, current_user.id, repo_name),
                     daemon=True).start()

    return jsonify({"ok": True, "job_id": job.id, "status": "queued"})


@bp.route("/api/jobs")
@login_required
def list_jobs():
    if current_user.active_plan != "PLUS" and not current_user.is_admin:
        abort(403)
    rows = (CodexJob.query.filter_by(user_id=current_user.id)
            .order_by(CodexJob.created_at.desc()).limit(50).all())
    return jsonify({"ok": True, "jobs": [
        {"id": j.id, "status": j.status, "prompt": j.prompt[:200],
         "repo_url": j.repo_url, "log": (j.log or "")[-2000:],
         "created_at": j.created_at.isoformat()}
        for j in rows
    ]})


@bp.route("/api/jobs/<int:jid>")
@login_required
def get_job(jid):
    j = CodexJob.query.get_or_404(jid)
    if j.user_id != current_user.id and not current_user.is_admin:
        abort(403)
    return jsonify({"ok": True, "job": {
        "id": j.id, "status": j.status, "prompt": j.prompt,
        "repo_url": j.repo_url, "log": j.log,
        "seconds_used": j.seconds_used,
        "created_at": j.created_at.isoformat(),
    }})


@bp.route("/api/wipe-history", methods=["POST"])
@login_required
def wipe_codex_history():
    chat = get_or_create_codex_chat(current_user)
    Message.query.filter_by(chat_id=chat.id).delete()
    db.session.commit()
    return jsonify({"ok": True})


# --- the real pipeline --------------------------------------------------------
def _gh(method, url, token, json_body=None, timeout=30):
    return requests.request(
        method, url,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        json=json_body, timeout=timeout,
    )


def _log(job, line):
    job.log = (job.log or "") + (line.rstrip() + "\n")
    db.session.commit()


def _run_codex_job(app, job_id, user_id, repo_name):
    """Background worker: AI → real GitHub repo → pushed files."""
    started = time.time()
    with app.app_context():
        job = CodexJob.query.get(job_id)
        user = User.query.get(user_id)
        try:
            token = user.github_token
            if not token:
                job.status = "error"
                _log(job, "GitHub token mavjud emas.")
                return

            # 1) Generate file manifest with AI -------------------------------
            job.status = "generating"
            db.session.commit()
            _log(job, "🤖 AI loyiha rejasini yaratmoqda...")

            codex_model = (AiModel.query.filter_by(is_codex=True, enabled=True).first()
                           or AiModel.query.filter_by(enabled=True, is_codex=False).first())
            if not codex_model:
                job.status = "error"
                _log(job, "Codex modeli sozlanmagan.")
                return

            sys = (
                "Sen Codex'sen — to'liq, ishlovchi loyiha yaratuvchi AI. "
                "Foydalanuvchi topshirig'iga muvofiq, to'liq ishlovchi va sinalgan "
                "loyihani tayyorla. Barcha kerakli fayllar (README.md, requirements/"
                "package.json, asosiy kod, yordamchi modullar) bo'lsin.\n\n"
                "Quyidagi formatda javob ber, boshqa hech narsa qo'shma:\n\n"
                "=== file: <fayl yo'li> ===\n"
                "<fayl mazmuni>\n"
                "=== file: <fayl yo'li> ===\n"
                "<fayl mazmuni>\n\n"
                "Hech qachon markdown code block (``` ``` ) ishlatma — fayl ichidagi "
                "mazmun bevosita yoziladi. Maksimal 25 ta fayl. Har bir fayl o'zining "
                "to'liq mazmuniga ega bo'lsin."
            )
            full_text = []
            res = ai_service.call_chat_stream(
                codex_model,
                [
                    {"role": "system", "content": sys},
                    {"role": "user", "content": job.prompt},
                ],
                on_token=lambda t: full_text.append(t),
                on_status=lambda s: _log(job, f"⏳ {s}"),
                max_retries=4,
            )
            if not res.get("ok"):
                job.status = "error"
                _log(job, f"AI xato: {res.get('error')}")
                return

            files = parse_files_from_ai("".join(full_text))
            _log(job, f"📁 {len(files)} ta fayl tayyor.")

            # 2) Create real GitHub repo --------------------------------------
            job.status = "creating-repo"
            db.session.commit()
            _log(job, f"📦 GitHub'da '{repo_name}' repository yaratilmoqda...")

            r = _gh("POST", f"{GITHUB_API}/user/repos", token, {
                "name": repo_name,
                "description": f"AurexAi Codex: {job.prompt[:140]}",
                "private": False,
                "auto_init": True,
            })
            # If name conflict, append timestamp
            if r.status_code == 422 and "already exists" in r.text.lower():
                repo_name = repo_name + "-" + datetime.utcnow().strftime("%H%M%S")
                _log(job, f"♻ Nom band, qayta urinish: {repo_name}")
                r = _gh("POST", f"{GITHUB_API}/user/repos", token, {
                    "name": repo_name,
                    "description": f"AurexAi Codex: {job.prompt[:140]}",
                    "private": False,
                    "auto_init": True,
                })
            if r.status_code >= 300:
                job.status = "error"
                _log(job, f"GitHub repo yaratishda xato {r.status_code}: {r.text[:300]}")
                return
            repo_data = r.json()
            owner = repo_data["owner"]["login"]
            html_url = repo_data["html_url"]
            job.repo_url = html_url
            db.session.commit()
            _log(job, f"✅ Repo yaratildi: {html_url}")

            # 3) Push each file via Contents API ------------------------------
            job.status = "pushing"
            db.session.commit()

            # Wait briefly for auto-init commit to be available
            time.sleep(2)

            for path, content in files:
                try:
                    encoded = base64.b64encode(content.encode("utf-8")).decode("ascii")
                except Exception as e:
                    _log(job, f"⚠ Fayl encoding xato {path}: {e}")
                    continue

                # Get existing sha (if file exists from auto_init like README.md)
                existing = _gh("GET",
                               f"{GITHUB_API}/repos/{owner}/{repo_name}/contents/{path}",
                               token)
                body = {
                    "message": f"AurexAi Codex: {path}",
                    "content": encoded,
                }
                if existing.status_code == 200:
                    body["sha"] = existing.json().get("sha")

                pr = _gh("PUT",
                         f"{GITHUB_API}/repos/{owner}/{repo_name}/contents/{path}",
                         token, body)
                if pr.status_code >= 300:
                    _log(job, f"⚠ {path} push xato {pr.status_code}: {pr.text[:200]}")
                else:
                    _log(job, f"📤 {path}")

            # 4) Done ---------------------------------------------------------
            job.status = "done"
            elapsed = int(time.time() - started)
            job.seconds_used = elapsed
            add_seconds(user_id, elapsed)
            _log(job, f"🎉 Tayyor! Vaqt: {elapsed}s")
            db.session.commit()

            # Save assistant message into the codex chat
            chat = get_or_create_codex_chat(user)
            summary = (
                f"✅ Loyihangiz tayyor!\n\n"
                f"🔗 {html_url}\n\n"
                f"📁 Fayllar: {len(files)}\n"
                f"⏱ Vaqt: {elapsed}s\n\n"
                f"Repository'ni clone qilib, lokalda ishga tushirsangiz bo'ladi."
            )
            db.session.add(Message(chat_id=chat.id, role="assistant",
                                   content=summary, model=codex_model.model_id))
            db.session.commit()

        except Exception as e:
            try:
                job.status = "error"
                _log(job, f"❌ Kutilmagan xato: {e}")
            except Exception:
                db.session.rollback()
